
DROP TABLE IF EXISTS Ecommerce.Producto;

CREATE TABLE Ecommerce.Producto (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    descripcion TEXT NOT NULL,
    imagen TEXT NOT NULL,
    id_Inventario BIGINT NOT NULL,
    id_Palabra_clave BIGINT NOT NULL,
    id_provedor BIGINT NOT NULL,
    id_Precio BIGINT NOT NULL,
    CONSTRAINT FK_INV FOREIGN KEY (id_Inventario) REFERENCES Ecommerce.Inventario(id),
    CONSTRAINT FK_PAL FOREIGN KEY (id_Palabra_clave) REFERENCES Ecommerce.Palabra_clave(id),
    CONSTRAINT FK_PROVE FOREIGN KEY (id_provedor) REFERENCES Ecommerce.provedor(id),
    CONSTRAINT FK_PRE FOREIGN KEY (id_Precio) REFERENCES  Ecommerce.Precio(id)
);

insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (1, 'Laptop Mac', 'mac con 1 gb de ram', 'http://thetimes.co.uk/lacinia/erat.png', 1, 1, 1, 1);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (2, 'Sueter balenciaga', 'sueter balenciaga de tenmu', 'http://wikipedia.org/id/lobortis/convallis/tortor/risus/dapibus.json', 2, 2, 2, 2);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (3, 'Silla ergonómica de oficina', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 'https://hao123.com/purus.js', 3, 3, 3, 3);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (4, 'Juego de cuchillos de cocina de acero inoxidable', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'https://bing.com/ut/volutpat.js', 4, 4, 4, 4);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (5, 'Cámara DSLR de alta resolución', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'http://auda.org.au/risus/dapibus/augue/vel/accumsan/tellus/nisi.jsp', 5, 5, 5, 5);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (6, 'Zapatillas para correr de alto rendimiento', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 'https://cpanel.net/blandit/mi/in/porttitor/pede.xml', 6, 6, 6, 6);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (7, 'Juego de mesa estratégico', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 'http://hao123.com/molestie.jpg', 7, 7, 7, 7);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (8, 'Lámpara de techo moderna LED', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 'https://shinystat.com/vestibulum/ante/ipsum/primis/in/faucibus.json', 8, 8, 8, 8);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (9, 'Collar de plata con colgante de piedra lunar', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 'https://foxnews.com/velit/id.aspx', 9, 9, 9, 9);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (10, 'Paleta de sombras de ojos de tonos cálidos', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 'http://hostgator.com/curabitur/at.jpg', 10, 10, 10, 10);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (11, 'Mochila resistente al agua para senderismo', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 'https://uol.com.br/adipiscing/elit/proin/risus/praesent/lectus.json', 1, 11, 11, 11);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (12, 'Herramientas de carpintería profesionales', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 'https://studiopress.com/donec/diam/neque.jpg', 2, 12, 12, 12);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (13, 'Juego de batería electrónica para principiantes', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 'https://oaic.gov.au/nibh/fusce/lacus/purus/aliquet/at.png', 3, 13, 13, 13);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (14, 'Robot aspirador con mapeo inteligente', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 'http://bizjournals.com/ridiculus/mus/vivamus/vestibulum/sagittis.jsp', 4, 14, 14, 14);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (15, 'Set de ollas y sartenes antiadherentes', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 'https://google.com/sagittis/sapien/cum/sociis/natoque/penatibus.html', 5, 15, 15, 15);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (16, 'Reloj inteligente con monitor de salud', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'https://uiuc.edu/varius/ut/blandit/non/interdum/in/ante.jsp', 6, 16, 16, 16);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (17, 'Libro de cocina de cocina étnica', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 'http://cam.ac.uk/vitae/ipsum/aliquam/non/mauris/morbi.aspx', 7, 17, 17, 17);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (18, 'Juego de bloques de construcción para niños', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'https://issuu.com/faucibus/cursus/urna/ut/tellus/nulla.html', 8, 18, 18, 18);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (19, 'Juego de vajilla de porcelana', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 'https://bbb.org/nam.xml', 9, 19, 19, 19);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (20, 'Kit de pintura al óleo para artistas aficionados', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 'https://thetimes.co.uk/eu/massa/donec.jpg', 10, 20, 20, 20);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (21, 'Cama para mascotas de diseño moderno', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'http://craigslist.org/ante/vivamus/tortor/duis.jsp', 1, 21, 21, 21);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (22, 'Bicicleta de montaña de aluminio', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 'http://umich.edu/tempus/vel.jpg', 2, 22, 22, 22);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (23, 'Maleta de viaje con ruedas giratorias', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'http://friendfeed.com/ut.jpg', 3, 23, 23, 23);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (24, 'Set de brochas de maquillaje profesional', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 'http://home.pl/congue/eget/semper/rutrum/nulla/nunc/purus.jsp', 4, 24, 24, 24);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (25, 'Guitarra acústica de gama media', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 'https://goo.gl/aliquam/erat/volutpat/in/congue/etiam/justo.html', 5, 25, 25, 25);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (26, 'Juego de toallas de baño de algodón orgánico', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 'https://aol.com/nunc.js', 6, 26, 26, 26);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (27, 'Set de herramientas de jardinería ergonómicas', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 'https://tumblr.com/sem/mauris/laoreet/ut.jpg', 7, 27, 27, 27);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (28, 'Escritorio de estudio minimalista', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'http://state.gov/ipsum/ac/tellus/semper/interdum/mauris/ullamcorper.xml', 8, 28, 28, 28);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (29, 'Teclado mecánico para jugadores', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 'http://g.co/imperdiet/sapien/urna.jsp', 9, 29, 29, 29);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (30, 'Tetera de cerámica con diseño floral', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 'http://google.com.br/dapibus/at/diam/nam/tristique.jpg', 10, 30, 30, 30);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (31, 'Juego de accesorios para coche de lujo', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'http://prlog.org/fermentum/justo/nec/condimentum/neque.jsp', 1, 31, 31, 31);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (32, 'Maletín de herramientas para reparaciones domésticas', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'http://ihg.com/tempus/semper/est/quam.html', 2, 32, 32, 32);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (33, 'Balón de fútbol de alta calidad', 'Fusce consequat. Nulla nisl. Nunc nisl.', 'https://google.com.hk/rhoncus/mauris/enim/leo/rhoncus.json', 3, 33, 33, 33);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (34, 'Sistema de altavoces Bluetooth portátil', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 'http://admin.ch/vestibulum/ante/ipsum/primis/in/faucibus/orci.jpg', 4, 34, 34, 34);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (35, 'Plancha de pelo profesional de titanio', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'https://answers.com/nibh/quisque/id/justo/sit/amet/sapien.html', 5, 35, 35, 35);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (36, 'Puzzle 3D de monumentos famosos', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 'https://mayoclinic.com/placerat/ante/nulla.xml', 6, 36, 36, 36);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (37, 'Abrebotellas eléctrico recargable', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 'https://unblog.fr/est/quam/pharetra/magna/ac.jsp', 7, 37, 37, 37);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (38, 'Máquina de coser computarizada', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'http://etsy.com/eget/massa/tempor.json', 8, 38, 38, 38);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (39, 'Set de vasos de whisky de cristal', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'https://google.ru/faucibus/cursus/urna/ut/tellus/nulla.xml', 9, 39, 39, 39);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (40, 'Bastón de trekking ultraligero', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 'https://dailymotion.com/viverra/pede/ac/diam/cras.aspx', 10, 40, 40, 40);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (41, 'Carrito de la compra plegable', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'http://adobe.com/iaculis/congue.json', 1, 41, 41, 41);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (42, 'Juego de sábanas de algodón egipcio', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 'https://wikimedia.org/mattis/pulvinar.xml', 2, 42, 42, 42);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (43, 'Micrófono de condensador para estudio de grabación', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 'https://wix.com/suspendisse/potenti/cras/in/purus.jsp', 3, 43, 43, 43);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (44, 'Tabla de paddle surf hinchable', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 'http://qq.com/et/ultrices/posuere.xml', 4, 44, 44, 44);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (45, 'Báscula de cocina digital precisa', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 'http://simplemachines.org/ut/massa/volutpat/convallis/morbi/odio.html', 5, 45, 45, 45);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (46, 'Set de figuras de acción coleccionables', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'https://china.com.cn/tristique.json', 6, 46, 46, 46);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (47, 'Cojines decorativos para el sofá', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 'https://amazon.co.uk/sit/amet/erat/nulla/tempus/vivamus.xml', 7, 47, 47, 47);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (48, 'Set de herramientas de barbacoa de acero inoxidable', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 'https://ted.com/pede/venenatis/non/sodales/sed/tincidunt.aspx', 8, 48, 48, 48);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (49, 'Juego de té de porcelana fina', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'https://mozilla.org/placerat/praesent/blandit.js', 9, 49, 49, 49);
insert into Ecommerce.Producto (id, nombre, descripcion, imagen, id_Inventario, id_Palabra_clave, id_provedor, id_Precio) values (50, 'Altavoz inteligente con asistente de voz', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'http://umn.edu/sit/amet.jsp', 10, 50, 50, 50);
