
DROP TABLE IF EXISTS Ecommerce.Seguimiento;

CREATE TABLE Ecommerce.Seguimiento (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ubicacion VARCHAR(255) NOT NULL,
    fecha_actualizacion DATE NOT NULL
);

insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (1, 'Chiapas', '1963/07/13');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (2, 'Hidalgo', '1990/09/11');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (3, 'Puebla', '2011/01/22');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (4, 'Durango', '1940/12/25');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (5, 'San Luis Potosí', '2013/12/24');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (6, 'Sonora', '1975/08/23');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (7, 'Hidalgo', '1940/02/13');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (8, 'Nayarit', '1932/09/18');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (9, 'Tamaulipas', '2013/03/02');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (10, 'Baja California Sur', '1902/02/25');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (11, 'Chihuahua', '1940/03/15');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (12, 'Morelos', '2021/05/02');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (13, 'Oaxaca', '1989/08/26');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (14, 'Tabasco', '1912/08/18');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (15, 'Michoacán', '1979/12/31');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (16, 'Chiapas', '1983/01/20');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (17, 'Sonora', '1922/11/19');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (18, 'Chihuahua', '2020/05/23');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (19, 'Baja California Sur', '1964/05/07');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (20, 'Chihuahua', '1968/07/30');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (21, 'Guanajuato', '1992/11/02');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (22, 'San Luis Potosí', '2000/12/25');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (23, 'Quintana Roo', '1937/04/16');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (24, 'Tlaxcala', '1964/01/10');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (25, 'Sinaloa', '1900/06/18');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (26, 'Jalisco', '1907/02/03');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (27, 'Quintana Roo', '1942/08/30');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (28, 'Oaxaca', '2009/04/20');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (29, 'Tamaulipas', '1920/12/26');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (30, 'Querétaro', '1917/08/17');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (31, 'Zacatecas', '1951/01/09');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (32, 'México', '1919/01/18');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (33, 'México', '2020/05/02');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (34, 'Tabasco', '1910/05/18');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (35, 'Campeche', '2018/07/28');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (36, 'Puebla', '1989/07/21');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (37, 'Hidalgo', '1928/11/02');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (38, 'México', '1967/01/02');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (39, 'Querétaro', '1959/12/29');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (40, 'Aguascalientes', '2008/06/03');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (41, 'Coahuila', '1992/05/03');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (42, 'Chiapas', '1997/04/26');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (43, 'Durango', '1922/07/15');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (44, 'Quintana Roo', '1952/10/25');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (45, 'Baja California Sur', '1916/02/11');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (46, 'Morelos', '1904/10/30');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (47, 'Tabasco', '1990/08/23');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (48, 'Jalisco', '1958/09/16');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (49, 'Hidalgo', '1953/06/20');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (50, 'Aguascalientes', '2004/12/29');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (51, 'Puebla', '1962/06/30');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (52, 'Campeche', '2014/10/02');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (53, 'Yucatán', '1942/09/15');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (54, 'Sonora', '1917/12/13');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (55, 'Nuevo León', '1975/11/25');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (56, 'Aguascalientes', '1944/01/21');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (57, 'Veracruz', '1981/08/27');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (58, 'San Luis Potosí', '1981/07/01');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (59, 'Durango', '1922/11/07');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (60, 'Sinaloa', '1921/11/21');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (61, 'Tamaulipas', '2002/12/17');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (62, 'Nayarit', '2015/11/09');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (63, 'Guerrero', '1915/11/14');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (64, 'Zacatecas', '1915/08/31');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (65, 'Coahuila', '1904/08/12');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (66, 'Guanajuato', '1972/05/12');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (67, 'Aguascalientes', '1967/06/12');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (68, 'Oaxaca', '1908/07/18');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (69, 'Coahuila', '1991/02/27');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (70, 'Nayarit', '1975/09/29');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (71, 'Sonora', '1955/04/14');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (72, 'Baja California', '1974/06/21');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (73, 'San Luis Potosí', '2001/12/25');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (74, 'Querétaro', '1919/11/15');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (75, 'Tamaulipas', '2004/04/20');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (76, 'Campeche', '1979/02/04');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (77, 'México', '1995/09/26');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (78, 'Jalisco', '1966/04/03');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (79, 'México', '1993/12/01');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (80, 'Oaxaca', '2005/02/15');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (81, 'México', '1928/02/12');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (82, 'Tlaxcala', '1920/02/03');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (83, 'Querétaro', '1912/08/06');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (84, 'Chihuahua', '2003/07/07');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (85, 'Chihuahua', '1969/10/17');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (86, 'Morelos', '2020/03/08');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (87, 'Chihuahua', '1943/08/09');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (88, 'Veracruz', '2000/06/21');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (89, 'Colima', '1924/11/11');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (90, 'Querétaro', '1964/04/24');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (91, 'Guanajuato', '1949/08/08');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (92, 'Guanajuato', '1966/09/29');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (93, 'Hidalgo', '1941/02/17');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (94, 'Chihuahua', '1977/01/02');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (95, 'Coahuila', '1966/12/27');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (96, 'San Luis Potosí', '2018/03/31');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (97, 'Querétaro', '1920/07/04');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (98, 'Tamaulipas', '1983/09/24');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (99, 'México', '1916/11/24');
insert into Ecommerce.Seguimiento (id, ubicacion, fecha_actualizacion) values (100, 'Tamaulipas', '1972/08/04');
