
DROP TABLE IF EXISTS Ecommerce.Metodo_pago;

CREATE TABLE Ecommerce.Metodo_pago (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    metodo VARCHAR(255) NOT NULL
);

insert into Ecommerce.Metodo_pago (id, metodo) values (1, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (2, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (3, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (4, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (5, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (6, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (7, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (8, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (9, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (10, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (11, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (12, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (13, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (14, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (15, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (16, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (17, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (18, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (19, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (20, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (21, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (22, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (23, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (24, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (25, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (26, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (27, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (28, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (29, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (30, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (31, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (32, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (33, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (34, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (35, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (36, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (37, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (38, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (39, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (40, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (41, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (42, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (43, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (44, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (45, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (46, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (47, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (48, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (49, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (50, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (51, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (52, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (53, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (54, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (55, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (56, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (57, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (58, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (59, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (60, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (61, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (62, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (63, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (64, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (65, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (66, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (67, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (68, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (69, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (70, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (71, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (72, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (73, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (74, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (75, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (76, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (77, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (78, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (79, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (80, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (81, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (82, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (83, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (84, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (85, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (86, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (87, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (88, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (89, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (90, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (91, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (92, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (93, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (94, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (95, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (96, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (97, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (98, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (99, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (100, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (101, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (102, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (103, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (104, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (105, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (106, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (107, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (108, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (109, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (110, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (111, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (112, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (113, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (114, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (115, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (116, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (117, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (118, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (119, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (120, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (121, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (122, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (123, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (124, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (125, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (126, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (127, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (128, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (129, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (130, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (131, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (132, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (133, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (134, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (135, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (136, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (137, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (138, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (139, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (140, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (141, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (142, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (143, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (144, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (145, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (146, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (147, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (148, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (149, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (150, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (151, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (152, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (153, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (154, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (155, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (156, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (157, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (158, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (159, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (160, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (161, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (162, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (163, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (164, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (165, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (166, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (167, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (168, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (169, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (170, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (171, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (172, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (173, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (174, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (175, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (176, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (177, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (178, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (179, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (180, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (181, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (182, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (183, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (184, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (185, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (186, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (187, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (188, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (189, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (190, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (191, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (192, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (193, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (194, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (195, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (196, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (197, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (198, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (199, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (200, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (201, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (202, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (203, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (204, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (205, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (206, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (207, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (208, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (209, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (210, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (211, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (212, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (213, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (214, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (215, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (216, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (217, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (218, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (219, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (220, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (221, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (222, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (223, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (224, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (225, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (226, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (227, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (228, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (229, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (230, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (231, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (232, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (233, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (234, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (235, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (236, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (237, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (238, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (239, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (240, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (241, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (242, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (243, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (244, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (245, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (246, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (247, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (248, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (249, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (250, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (251, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (252, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (253, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (254, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (255, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (256, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (257, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (258, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (259, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (260, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (261, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (262, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (263, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (264, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (265, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (266, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (267, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (268, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (269, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (270, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (271, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (272, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (273, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (274, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (275, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (276, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (277, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (278, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (279, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (280, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (281, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (282, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (283, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (284, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (285, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (286, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (287, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (288, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (289, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (290, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (291, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (292, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (293, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (294, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (295, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (296, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (297, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (298, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (299, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (300, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (301, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (302, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (303, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (304, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (305, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (306, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (307, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (308, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (309, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (310, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (311, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (312, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (313, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (314, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (315, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (316, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (317, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (318, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (319, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (320, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (321, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (322, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (323, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (324, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (325, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (326, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (327, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (328, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (329, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (330, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (331, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (332, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (333, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (334, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (335, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (336, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (337, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (338, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (339, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (340, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (341, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (342, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (343, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (344, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (345, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (346, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (347, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (348, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (349, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (350, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (351, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (352, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (353, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (354, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (355, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (356, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (357, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (358, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (359, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (360, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (361, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (362, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (363, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (364, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (365, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (366, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (367, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (368, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (369, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (370, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (371, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (372, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (373, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (374, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (375, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (376, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (377, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (378, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (379, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (380, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (381, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (382, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (383, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (384, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (385, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (386, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (387, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (388, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (389, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (390, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (391, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (392, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (393, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (394, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (395, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (396, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (397, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (398, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (399, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (400, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (401, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (402, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (403, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (404, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (405, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (406, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (407, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (408, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (409, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (410, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (411, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (412, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (413, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (414, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (415, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (416, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (417, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (418, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (419, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (420, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (421, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (422, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (423, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (424, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (425, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (426, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (427, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (428, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (429, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (430, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (431, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (432, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (433, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (434, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (435, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (436, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (437, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (438, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (439, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (440, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (441, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (442, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (443, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (444, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (445, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (446, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (447, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (448, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (449, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (450, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (451, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (452, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (453, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (454, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (455, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (456, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (457, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (458, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (459, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (460, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (461, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (462, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (463, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (464, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (465, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (466, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (467, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (468, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (469, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (470, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (471, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (472, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (473, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (474, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (475, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (476, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (477, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (478, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (479, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (480, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (481, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (482, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (483, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (484, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (485, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (486, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (487, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (488, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (489, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (490, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (491, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (492, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (493, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (494, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (495, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (496, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (497, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (498, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (499, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (500, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (501, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (502, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (503, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (504, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (505, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (506, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (507, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (508, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (509, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (510, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (511, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (512, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (513, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (514, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (515, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (516, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (517, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (518, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (519, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (520, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (521, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (522, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (523, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (524, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (525, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (526, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (527, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (528, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (529, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (530, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (531, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (532, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (533, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (534, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (535, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (536, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (537, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (538, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (539, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (540, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (541, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (542, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (543, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (544, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (545, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (546, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (547, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (548, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (549, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (550, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (551, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (552, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (553, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (554, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (555, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (556, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (557, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (558, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (559, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (560, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (561, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (562, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (563, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (564, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (565, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (566, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (567, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (568, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (569, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (570, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (571, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (572, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (573, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (574, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (575, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (576, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (577, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (578, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (579, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (580, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (581, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (582, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (583, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (584, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (585, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (586, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (587, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (588, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (589, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (590, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (591, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (592, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (593, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (594, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (595, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (596, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (597, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (598, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (599, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (600, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (601, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (602, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (603, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (604, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (605, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (606, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (607, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (608, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (609, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (610, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (611, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (612, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (613, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (614, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (615, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (616, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (617, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (618, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (619, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (620, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (621, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (622, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (623, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (624, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (625, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (626, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (627, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (628, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (629, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (630, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (631, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (632, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (633, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (634, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (635, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (636, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (637, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (638, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (639, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (640, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (641, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (642, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (643, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (644, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (645, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (646, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (647, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (648, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (649, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (650, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (651, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (652, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (653, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (654, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (655, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (656, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (657, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (658, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (659, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (660, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (661, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (662, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (663, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (664, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (665, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (666, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (667, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (668, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (669, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (670, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (671, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (672, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (673, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (674, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (675, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (676, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (677, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (678, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (679, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (680, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (681, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (682, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (683, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (684, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (685, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (686, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (687, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (688, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (689, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (690, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (691, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (692, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (693, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (694, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (695, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (696, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (697, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (698, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (699, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (700, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (701, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (702, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (703, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (704, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (705, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (706, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (707, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (708, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (709, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (710, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (711, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (712, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (713, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (714, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (715, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (716, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (717, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (718, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (719, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (720, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (721, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (722, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (723, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (724, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (725, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (726, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (727, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (728, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (729, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (730, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (731, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (732, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (733, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (734, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (735, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (736, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (737, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (738, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (739, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (740, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (741, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (742, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (743, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (744, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (745, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (746, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (747, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (748, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (749, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (750, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (751, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (752, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (753, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (754, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (755, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (756, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (757, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (758, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (759, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (760, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (761, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (762, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (763, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (764, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (765, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (766, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (767, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (768, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (769, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (770, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (771, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (772, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (773, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (774, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (775, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (776, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (777, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (778, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (779, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (780, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (781, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (782, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (783, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (784, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (785, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (786, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (787, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (788, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (789, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (790, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (791, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (792, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (793, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (794, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (795, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (796, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (797, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (798, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (799, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (800, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (801, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (802, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (803, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (804, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (805, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (806, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (807, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (808, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (809, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (810, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (811, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (812, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (813, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (814, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (815, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (816, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (817, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (818, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (819, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (820, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (821, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (822, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (823, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (824, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (825, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (826, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (827, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (828, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (829, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (830, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (831, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (832, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (833, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (834, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (835, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (836, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (837, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (838, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (839, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (840, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (841, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (842, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (843, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (844, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (845, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (846, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (847, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (848, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (849, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (850, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (851, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (852, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (853, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (854, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (855, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (856, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (857, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (858, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (859, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (860, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (861, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (862, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (863, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (864, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (865, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (866, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (867, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (868, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (869, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (870, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (871, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (872, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (873, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (874, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (875, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (876, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (877, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (878, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (879, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (880, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (881, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (882, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (883, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (884, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (885, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (886, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (887, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (888, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (889, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (890, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (891, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (892, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (893, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (894, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (895, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (896, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (897, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (898, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (899, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (900, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (901, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (902, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (903, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (904, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (905, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (906, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (907, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (908, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (909, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (910, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (911, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (912, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (913, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (914, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (915, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (916, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (917, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (918, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (919, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (920, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (921, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (922, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (923, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (924, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (925, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (926, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (927, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (928, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (929, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (930, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (931, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (932, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (933, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (934, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (935, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (936, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (937, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (938, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (939, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (940, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (941, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (942, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (943, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (944, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (945, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (946, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (947, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (948, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (949, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (950, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (951, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (952, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (953, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (954, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (955, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (956, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (957, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (958, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (959, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (960, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (961, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (962, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (963, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (964, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (965, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (966, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (967, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (968, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (969, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (970, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (971, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (972, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (973, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (974, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (975, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (976, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (977, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (978, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (979, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (980, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (981, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (982, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (983, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (984, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (985, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (986, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (987, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (988, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (989, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (990, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (991, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (992, 'PayPal');
insert into Ecommerce.Metodo_pago (id, metodo) values (993, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (994, 'Transferencia bancaria');
insert into Ecommerce.Metodo_pago (id, metodo) values (995, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (996, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (997, 'Tarjeta de crédito');
insert into Ecommerce.Metodo_pago (id, metodo) values (998, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (999, 'Efectivo');
insert into Ecommerce.Metodo_pago (id, metodo) values (1000, 'Efectivo');
